<?php

namespace ContainerEOxkeXF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllernewCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nLnEcBQ.App\Controller\CommentController::newComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nLnEcBQ.App\\Controller\\CommentController::newComment()'] = ($container->privates['.service_locator.nLnEcBQ'] ?? $container->load('get_ServiceLocator_NLnEcBQService'))->withContext('App\\Controller\\CommentController::newComment()', $container);
    }
}
