<?php

namespace ContainerOU65gZo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandControllergetAllOrdersService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.rT8TQD7.App\Controller\CommandController::getAllOrders()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rT8TQD7.App\\Controller\\CommandController::getAllOrders()'] = ($container->privates['.service_locator.rT8TQD7'] ?? $container->load('get_ServiceLocator_RT8TQD7Service'))->withContext('App\\Controller\\CommandController::getAllOrders()', $container);
    }
}
