<?php

namespace ContainerOU65gZo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoProductControllerexecuteAddPhotoService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.YF1FmtY.App\Controller\PhotoProductController::executeAddPhoto()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YF1FmtY.App\\Controller\\PhotoProductController::executeAddPhoto()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'photoProductService' => ['privates', 'App\\Service\\PhotoProductService', 'getPhotoProductServiceService', true],
        ], [
            'photoProductService' => 'App\\Service\\PhotoProductService',
        ]))->withContext('App\\Controller\\PhotoProductController::executeAddPhoto()', $container);
    }
}
