<?php

namespace ContainerOU65gZo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PaymentController' shared autowired service.
     *
     * @return \App\Controller\PaymentController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        $container->services['App\\Controller\\PaymentController'] = $instance = new \App\Controller\PaymentController(new \App\Service\CinetPayService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('CINETPAY_API_KEY'), $container->getEnv('CINETPAY_SITE_ID'), $container->getEnv('CINETPAY_RETURN_URL'), $container->getEnv('CINETPAY_NOTIFY_URL'), $container->getEnv('CINETPAY_CHECK_URL'), $container->getEnv('CINETPAY_PAYMENT_URL'), $a), $a);

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\PaymentController', $container));

        return $instance;
    }
}
