<?php

namespace ContainerOU65gZo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerdeleteUserService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.hz.RJka.App\Controller\UserController::deleteUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hz.RJka.App\\Controller\\UserController::deleteUser()'] = ($container->privates['.service_locator.hz.RJka'] ?? $container->load('get_ServiceLocator_Hz_RJkaService'))->withContext('App\\Controller\\UserController::deleteUser()', $container);
    }
}
