<?php

namespace ContainerOnZxlBy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatsControllergetStatsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ke.SD8W.App\Controller\StatsController::getStats()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ke.SD8W.App\\Controller\\StatsController::getStats()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userService' => ['privates', 'App\\Service\\UserService', 'getUserServiceService', true],
            'commentService' => ['privates', 'App\\Service\\CommentService', 'getCommentServiceService', true],
            'commandService' => ['privates', 'App\\Service\\CommandService', 'getCommandServiceService', true],
            'productService' => ['privates', 'App\\Service\\ProductService', 'getProductServiceService', true],
        ], [
            'userService' => 'App\\Service\\UserService',
            'commentService' => 'App\\Service\\CommentService',
            'commandService' => 'App\\Service\\CommandService',
            'productService' => 'App\\Service\\ProductService',
        ]))->withContext('App\\Controller\\StatsController::getStats()', $container);
    }
}
