<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBkSjAZ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBkSjAZ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOBkSjAZ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOBkSjAZ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOBkSjAZ\App_KernelProdContainer([
    'container.build_hash' => 'OBkSjAZ',
    'container.build_id' => 'a87f52ec',
    'container.build_time' => 1741294514,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBkSjAZ');
