<?php

namespace ContainerOBkSjAZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CommandRepository' shared autowired service.
     *
     * @return \App\Repository\CommandRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CommandRepository'] = new \App\Repository\CommandRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
