<?php

namespace ContainerOBkSjAZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhotoProductServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\PhotoProductService' shared autowired service.
     *
     * @return \App\Service\PhotoProductService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\PhotoProductService'] = new \App\Service\PhotoProductService(new \App\Service\ImgBBService($container->getEnv('IMGBB_API_KEY')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
