<?php

namespace ContainerOBkSjAZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReplyRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ReplyRepository' shared autowired service.
     *
     * @return \App\Repository\ReplyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ReplyRepository'] = new \App\Repository\ReplyRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
