<?php

namespace ContainerOBkSjAZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReplyControlleraddReplyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.zmiuSf5.App\Controller\ReplyController::addReply()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zmiuSf5.App\\Controller\\ReplyController::addReply()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'replyService' => ['privates', 'App\\Service\\ReplyService', 'getReplyServiceService', true],
        ], [
            'replyService' => 'App\\Service\\ReplyService',
        ]))->withContext('App\\Controller\\ReplyController::addReply()', $container);
    }
}
