<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'codeExpiresAt' => [parent::class, 'codeExpiresAt', null],
        "\0".parent::class."\0".'commands' => [parent::class, 'commands', null],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'numero_Tel' => [parent::class, 'numero_Tel', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'replies' => [parent::class, 'replies', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'typeUser' => [parent::class, 'typeUser', null],
        "\0".parent::class."\0".'validationCode' => [parent::class, 'validationCode', null],
        'address' => [parent::class, 'address', null],
        'codeExpiresAt' => [parent::class, 'codeExpiresAt', null],
        'commands' => [parent::class, 'commands', null],
        'comments' => [parent::class, 'comments', null],
        'email' => [parent::class, 'email', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'isActive' => [parent::class, 'isActive', null],
        'lastname' => [parent::class, 'lastname', null],
        'numero_Tel' => [parent::class, 'numero_Tel', null],
        'password' => [parent::class, 'password', null],
        'replies' => [parent::class, 'replies', null],
        'roles' => [parent::class, 'roles', null],
        'typeUser' => [parent::class, 'typeUser', null],
        'validationCode' => [parent::class, 'validationCode', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
