<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reply extends \App\Entity\Reply implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'idAdmin' => [parent::class, 'idAdmin', null],
        "\0".parent::class."\0".'idComment' => [parent::class, 'idComment', null],
        "\0".parent::class."\0".'replyAt' => [parent::class, 'replyAt', null],
        "\0".parent::class."\0".'response' => [parent::class, 'response', null],
        'id' => [parent::class, 'id', null],
        'idAdmin' => [parent::class, 'idAdmin', null],
        'idComment' => [parent::class, 'idComment', null],
        'replyAt' => [parent::class, 'replyAt', null],
        'response' => [parent::class, 'response', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
