<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'detailsCommands' => [parent::class, 'detailsCommands', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'idCat' => [parent::class, 'idCat', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null],
        "\0".parent::class."\0".'sendPhotos' => [parent::class, 'sendPhotos', null],
        "\0".parent::class."\0".'stock' => [parent::class, 'stock', null],
        'description' => [parent::class, 'description', null],
        'detailsCommands' => [parent::class, 'detailsCommands', null],
        'id' => [parent::class, 'id', null],
        'idCat' => [parent::class, 'idCat', null],
        'name' => [parent::class, 'name', null],
        'price' => [parent::class, 'price', null],
        'sendPhotos' => [parent::class, 'sendPhotos', null],
        'stock' => [parent::class, 'stock', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
